apiVersion: v2
name: nx-cloud
description: A Helm chart for Nrwl Nx Cloud
type: application
version: 0.0.2
dependencies:
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 13.18.5
    condition: mongodb.enabled
  - name: nx-cloud
    repository: https://nrwl.github.io/nx-cloud-helm
    version: 0.15.17
